import { MigrationInterface, QueryRunner } from "typeorm";

export class UpdateFlightEntities1773839095875 implements MigrationInterface {
    name = 'UpdateFlightEntities1773839095875'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_role_permissions_permission"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_role_permissions_role"`);
        await queryRunner.query(`ALTER TABLE "user_preferences" DROP CONSTRAINT "FK_user_preferences_user"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_users_role"`);
        await queryRunner.query(`ALTER TABLE "flight_history" DROP CONSTRAINT "flight_history_user_id_foreign"`);
        await queryRunner.query(`ALTER TABLE "favorite_destinations" DROP CONSTRAINT "favorite_destinations_airport_icao_foreign"`);
        await queryRunner.query(`ALTER TABLE "favorite_destinations" DROP CONSTRAINT "favorite_destinations_user_id_foreign"`);
        await queryRunner.query(`ALTER TABLE "custom_flight_simulations" DROP CONSTRAINT "custom_flight_simulations_arrival_airport_icao_foreign"`);
        await queryRunner.query(`ALTER TABLE "custom_flight_simulations" DROP CONSTRAINT "custom_flight_simulations_departure_airport_icao_foreign"`);
        await queryRunner.query(`ALTER TABLE "custom_flight_simulations" DROP CONSTRAINT "custom_flight_simulations_status_id_foreign"`);
        await queryRunner.query(`ALTER TABLE "custom_flight_simulations" DROP CONSTRAINT "custom_flight_simulations_user_id_foreign"`);
        await queryRunner.query(`ALTER TABLE "tracked_flights" DROP CONSTRAINT "tracked_flights_flight_id_foreign"`);
        await queryRunner.query(`ALTER TABLE "tracked_flights" DROP CONSTRAINT "tracked_flights_source_id_foreign"`);
        await queryRunner.query(`ALTER TABLE "tracked_flights" DROP CONSTRAINT "tracked_flights_tracking_status_id_foreign"`);
        await queryRunner.query(`ALTER TABLE "tracked_flights" DROP CONSTRAINT "tracked_flights_user_id_foreign"`);
        await queryRunner.query(`ALTER TABLE "flight_status_changes" DROP CONSTRAINT "flight_status_changes_change_type_id_foreign"`);
        await queryRunner.query(`ALTER TABLE "flight_status_changes" DROP CONSTRAINT "flight_status_changes_tracked_flight_id_foreign"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_flight_history_user_id_travel_date"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_flight_status_changes_tracked_flight_id_occurred_at"`);
        await queryRunner.query(`ALTER TABLE "favorite_destinations" DROP CONSTRAINT "favorite_destinations_user_id_airport_icao_unique"`);
        await queryRunner.query(`ALTER TABLE "tracked_flights" DROP CONSTRAINT "tracked_flights_user_id_flight_id_started_tracking_at_unique"`);
        await queryRunner.query(`ALTER TABLE "flights" DROP CONSTRAINT "FK_90ecb5fe51f3e8f270d126c5aed"`);
        await queryRunner.query(`ALTER TABLE "flights" DROP CONSTRAINT "FK_f434d3da290ac8e5bab0f0f8c9b"`);
        await queryRunner.query(`ALTER TABLE "flights" DROP CONSTRAINT "FK_66789ae7bdf01144dd2ae8dc10a"`);
        await queryRunner.query(`ALTER TABLE "flights" ALTER COLUMN "operating_airline_icao" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "flights" ALTER COLUMN "origin_icao" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "flights" ALTER COLUMN "destination_icao" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "flights" ALTER COLUMN "scheduled_out" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "flights" ALTER COLUMN "scheduled_in" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "flight_history" ALTER COLUMN "created_at" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "flight_history" ALTER COLUMN "updated_at" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "favorite_destinations" ALTER COLUMN "created_at" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "favorite_destinations" ALTER COLUMN "updated_at" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "custom_flight_simulations" ALTER COLUMN "created_at" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "custom_flight_simulations" ALTER COLUMN "updated_at" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "tracked_flights" ALTER COLUMN "started_tracking_at" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "tracked_flights" ALTER COLUMN "created_at" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "flight_status_changes" ALTER COLUMN "created_at" DROP DEFAULT`);
        await queryRunner.query(`CREATE INDEX "IDX_35db242a805855ae374834fd9f" ON "airports" ("city_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_549521bb9954d14e4303256f75" ON "airports" USING GiST ("location") `);
        await queryRunner.query(`CREATE INDEX "IDX_36b7590678c98e71c292f33839" ON "cities" ("country_code") `);
        await queryRunner.query(`CREATE INDEX "IDX_f09b946e49a6d0dddd5141c363" ON "flight_codeshares" ("marketing_airline_icao") `);
        await queryRunner.query(`CREATE INDEX "IDX_19aee178ec277f23f0cf59f69a" ON "flight_telemetry" ("location") `);
        await queryRunner.query(`CREATE INDEX "IDX_950ec3c7c9552423313449a663" ON "flights" ("ident_icao") `);
        await queryRunner.query(`CREATE INDEX "IDX_dc0b701d2abd870af5dd7a841f" ON "flights" ("callsign") `);
        await queryRunner.query(`CREATE INDEX "IDX_839e382e2d4794ca791771b6d6" ON "flights" ("status_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_2223b12c679eaac268e7f90976" ON "flights" ("scheduled_out") `);
        await queryRunner.query(`ALTER TABLE "tracked_flights" ADD CONSTRAINT "UQ_fbdb91293950606f5253039a5d6" UNIQUE ("user_id", "flight_id", "started_tracking_at")`);
        await queryRunner.query(`ALTER TABLE "flights" ADD CONSTRAINT "FK_90ecb5fe51f3e8f270d126c5aed" FOREIGN KEY ("operating_airline_icao") REFERENCES "airlines"("icao_code") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "flights" ADD CONSTRAINT "FK_f434d3da290ac8e5bab0f0f8c9b" FOREIGN KEY ("origin_icao") REFERENCES "airports"("icao_code") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "flights" ADD CONSTRAINT "FK_66789ae7bdf01144dd2ae8dc10a" FOREIGN KEY ("destination_icao") REFERENCES "airports"("icao_code") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_178199805b901ccd220ab7740ec" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_17022daf3f885f7d35423e9971e" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_preferences" ADD CONSTRAINT "FK_458057fa75b66e68a275647da2e" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "flight_history" ADD CONSTRAINT "FK_fe02c6d48735ac70f387141e48a" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "favorite_destinations" ADD CONSTRAINT "FK_18815a2ad3a6975ca15094a625a" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "favorite_destinations" ADD CONSTRAINT "FK_1e3b4167e337c27ba74c6606244" FOREIGN KEY ("airport_icao") REFERENCES "airports"("icao_code") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "custom_flight_simulations" ADD CONSTRAINT "FK_d289daa10fd1fca2b28de589a45" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "custom_flight_simulations" ADD CONSTRAINT "FK_c9d9513a88cf2df1f1d0838c7b2" FOREIGN KEY ("departure_airport_icao") REFERENCES "airports"("icao_code") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "custom_flight_simulations" ADD CONSTRAINT "FK_30d2deca96653c36922d625c702" FOREIGN KEY ("arrival_airport_icao") REFERENCES "airports"("icao_code") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "custom_flight_simulations" ADD CONSTRAINT "FK_669b85473b0363d3c586d6a7803" FOREIGN KEY ("status_id") REFERENCES "simulation_statuses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tracked_flights" ADD CONSTRAINT "FK_4aa75c55679a368b613ae884bc1" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tracked_flights" ADD CONSTRAINT "FK_11d4f88a5ff208a76ab1c06d5ab" FOREIGN KEY ("flight_id") REFERENCES "flights"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tracked_flights" ADD CONSTRAINT "FK_c3d7c075dcf62751ffbac14fb29" FOREIGN KEY ("tracking_status_id") REFERENCES "tracking_statuses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tracked_flights" ADD CONSTRAINT "FK_a547c98f02bcf8b0ca916d6df5c" FOREIGN KEY ("source_id") REFERENCES "tracking_sources"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "flight_status_changes" ADD CONSTRAINT "FK_39ec3703904e9abd01d9c9d95d9" FOREIGN KEY ("tracked_flight_id") REFERENCES "tracked_flights"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "flight_status_changes" ADD CONSTRAINT "FK_19a108d9a4c856a404a80cec486" FOREIGN KEY ("change_type_id") REFERENCES "flight_change_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "flight_status_changes" DROP CONSTRAINT "FK_19a108d9a4c856a404a80cec486"`);
        await queryRunner.query(`ALTER TABLE "flight_status_changes" DROP CONSTRAINT "FK_39ec3703904e9abd01d9c9d95d9"`);
        await queryRunner.query(`ALTER TABLE "tracked_flights" DROP CONSTRAINT "FK_a547c98f02bcf8b0ca916d6df5c"`);
        await queryRunner.query(`ALTER TABLE "tracked_flights" DROP CONSTRAINT "FK_c3d7c075dcf62751ffbac14fb29"`);
        await queryRunner.query(`ALTER TABLE "tracked_flights" DROP CONSTRAINT "FK_11d4f88a5ff208a76ab1c06d5ab"`);
        await queryRunner.query(`ALTER TABLE "tracked_flights" DROP CONSTRAINT "FK_4aa75c55679a368b613ae884bc1"`);
        await queryRunner.query(`ALTER TABLE "custom_flight_simulations" DROP CONSTRAINT "FK_669b85473b0363d3c586d6a7803"`);
        await queryRunner.query(`ALTER TABLE "custom_flight_simulations" DROP CONSTRAINT "FK_30d2deca96653c36922d625c702"`);
        await queryRunner.query(`ALTER TABLE "custom_flight_simulations" DROP CONSTRAINT "FK_c9d9513a88cf2df1f1d0838c7b2"`);
        await queryRunner.query(`ALTER TABLE "custom_flight_simulations" DROP CONSTRAINT "FK_d289daa10fd1fca2b28de589a45"`);
        await queryRunner.query(`ALTER TABLE "favorite_destinations" DROP CONSTRAINT "FK_1e3b4167e337c27ba74c6606244"`);
        await queryRunner.query(`ALTER TABLE "favorite_destinations" DROP CONSTRAINT "FK_18815a2ad3a6975ca15094a625a"`);
        await queryRunner.query(`ALTER TABLE "flight_history" DROP CONSTRAINT "FK_fe02c6d48735ac70f387141e48a"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1"`);
        await queryRunner.query(`ALTER TABLE "user_preferences" DROP CONSTRAINT "FK_458057fa75b66e68a275647da2e"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_17022daf3f885f7d35423e9971e"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_178199805b901ccd220ab7740ec"`);
        await queryRunner.query(`ALTER TABLE "flights" DROP CONSTRAINT "FK_66789ae7bdf01144dd2ae8dc10a"`);
        await queryRunner.query(`ALTER TABLE "flights" DROP CONSTRAINT "FK_f434d3da290ac8e5bab0f0f8c9b"`);
        await queryRunner.query(`ALTER TABLE "flights" DROP CONSTRAINT "FK_90ecb5fe51f3e8f270d126c5aed"`);
        await queryRunner.query(`ALTER TABLE "tracked_flights" DROP CONSTRAINT "UQ_fbdb91293950606f5253039a5d6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2223b12c679eaac268e7f90976"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_839e382e2d4794ca791771b6d6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dc0b701d2abd870af5dd7a841f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_950ec3c7c9552423313449a663"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_19aee178ec277f23f0cf59f69a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f09b946e49a6d0dddd5141c363"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_36b7590678c98e71c292f33839"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_549521bb9954d14e4303256f75"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_35db242a805855ae374834fd9f"`);
        await queryRunner.query(`ALTER TABLE "flight_status_changes" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "tracked_flights" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "tracked_flights" ALTER COLUMN "started_tracking_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "custom_flight_simulations" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "custom_flight_simulations" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "favorite_destinations" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "favorite_destinations" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "flight_history" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "flight_history" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "flights" ALTER COLUMN "scheduled_in" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "flights" ALTER COLUMN "scheduled_out" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "flights" ALTER COLUMN "destination_icao" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "flights" ALTER COLUMN "origin_icao" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "flights" ALTER COLUMN "operating_airline_icao" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "flights" ADD CONSTRAINT "FK_66789ae7bdf01144dd2ae8dc10a" FOREIGN KEY ("destination_icao") REFERENCES "airports"("icao_code") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "flights" ADD CONSTRAINT "FK_f434d3da290ac8e5bab0f0f8c9b" FOREIGN KEY ("origin_icao") REFERENCES "airports"("icao_code") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "flights" ADD CONSTRAINT "FK_90ecb5fe51f3e8f270d126c5aed" FOREIGN KEY ("operating_airline_icao") REFERENCES "airlines"("icao_code") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tracked_flights" ADD CONSTRAINT "tracked_flights_user_id_flight_id_started_tracking_at_unique" UNIQUE ("user_id", "flight_id", "started_tracking_at")`);
        await queryRunner.query(`ALTER TABLE "favorite_destinations" ADD CONSTRAINT "favorite_destinations_user_id_airport_icao_unique" UNIQUE ("user_id", "airport_icao")`);
        await queryRunner.query(`CREATE INDEX "IDX_flight_status_changes_tracked_flight_id_occurred_at" ON "flight_status_changes" ("occurred_at", "tracked_flight_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_flight_history_user_id_travel_date" ON "flight_history" ("travel_date", "user_id") `);
        await queryRunner.query(`ALTER TABLE "flight_status_changes" ADD CONSTRAINT "flight_status_changes_tracked_flight_id_foreign" FOREIGN KEY ("tracked_flight_id") REFERENCES "tracked_flights"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "flight_status_changes" ADD CONSTRAINT "flight_status_changes_change_type_id_foreign" FOREIGN KEY ("change_type_id") REFERENCES "flight_change_types"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tracked_flights" ADD CONSTRAINT "tracked_flights_user_id_foreign" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tracked_flights" ADD CONSTRAINT "tracked_flights_tracking_status_id_foreign" FOREIGN KEY ("tracking_status_id") REFERENCES "tracking_statuses"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tracked_flights" ADD CONSTRAINT "tracked_flights_source_id_foreign" FOREIGN KEY ("source_id") REFERENCES "tracking_sources"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tracked_flights" ADD CONSTRAINT "tracked_flights_flight_id_foreign" FOREIGN KEY ("flight_id") REFERENCES "flights"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "custom_flight_simulations" ADD CONSTRAINT "custom_flight_simulations_user_id_foreign" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "custom_flight_simulations" ADD CONSTRAINT "custom_flight_simulations_status_id_foreign" FOREIGN KEY ("status_id") REFERENCES "simulation_statuses"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "custom_flight_simulations" ADD CONSTRAINT "custom_flight_simulations_departure_airport_icao_foreign" FOREIGN KEY ("departure_airport_icao") REFERENCES "airports"("icao_code") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "custom_flight_simulations" ADD CONSTRAINT "custom_flight_simulations_arrival_airport_icao_foreign" FOREIGN KEY ("arrival_airport_icao") REFERENCES "airports"("icao_code") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "favorite_destinations" ADD CONSTRAINT "favorite_destinations_user_id_foreign" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "favorite_destinations" ADD CONSTRAINT "favorite_destinations_airport_icao_foreign" FOREIGN KEY ("airport_icao") REFERENCES "airports"("icao_code") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "flight_history" ADD CONSTRAINT "flight_history_user_id_foreign" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_users_role" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_preferences" ADD CONSTRAINT "FK_user_preferences_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_role_permissions_role" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_role_permissions_permission" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
