name: Reusable Application Deployment
on:
  workflow_call:
    inputs:
      skip_docker_build:
        description: "Skip building and pushing new Docker images"
        required: false
        type: boolean
        default: false
      vm_host:
        required: true
        type: string
      backend_url:
        required: true
        type: string
      frontend_url:
        required: true
        type: string
      resource_group_name:
        required: true
        type: string
      backend_app_name:
        required: true
        type: string
      frontend_app_name:
        required: true
        type: string
      backend_docker_image:
        required: false
        type: string
        default: "szerlok/flightanalytics-backend"
      frontend_docker_image:
        required: false
        type: string
        default: "szerlok/flightanalytics-frontend"
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
      DB_USER:
        required: true
      DB_PASSWORD:
        required: true
      JWT_SECRET:
        required: true
      AEROAPI_KEY:
        required: true
      OPENSKY_CLIENT_ID:
        required: true
      OPENSKY_CLIENT_SECRET:
        required: true
      CSRF_SECRET:
        required: true
      SMTP_HOST:
        required: true
      SMTP_PORT:
        required: true
      SMTP_SECURE:
        required: true
      SMTP_USER:
        required: true
      SMTP_PASSWORD:
        required: true
      MAIL_FROM:
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  # Frontend
  frontend:
    name: Build, Push and Deploy Frontend
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Login to Docker Hub
        if: ${{ !inputs.skip_docker_build }}
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        if: ${{ !inputs.skip_docker_build }}
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/deploy/Dockerfile
          push: true
          target: prod
          build-args:
            INTERNAL_API_URL=https://${{ inputs.backend_url }}
          tags: |
            ${{ inputs.frontend_docker_image }}:${{ github.sha }}
            ${{ github.ref == 'refs/heads/master' && format('{0}:latest', inputs.frontend_docker_image) || '' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Azure Login
        uses: azure/login@v3
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Update Azure App Service Container Image
        run: |
          az webapp config container set \
          --name ${{ inputs.frontend_app_name }} \
          --resource-group ${{ inputs.resource_group_name }} \
          --docker-custom-image-name ${{ inputs.frontend_docker_image }}:${{ github.sha }} \
          --docker-registry-server-url https://index.docker.io/v1/

  # Database setup:
  database-setup:
    name: Prepare Database VM
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "24"
          cache: 'npm'
          cache-dependency-path: ./backend/package-lock.json

      - name: Install Dependencies
        working-directory: ./backend
        run: npm ci

      - name: Wait for DB port
        env:
          VM_HOST: ${{ inputs.vm_host }}
        run: |
          timeout 300s bash -c 'until printf "" 2>>/dev/null >/dev/tcp/$VM_HOST/5432; do sleep 2; done'
          
      - name: Run Migrations and Seeding
        working-directory: ./backend
        env:
          DB_HOST: ${{ inputs.vm_host }}
          DB_PORT: 5432
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: "flight_db"
        run: npm run ci:migrate-and-seed

  # Backend
  backend:
    name: Build, Push and Deploy Containerized Backend
    needs: [database-setup]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Login to Docker Hub
        if: ${{ !inputs.skip_docker_build }}
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        if: ${{ !inputs.skip_docker_build }}
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/deploy/Dockerfile
          push: true
          target: prod
          tags: |
            ${{ inputs.backend_docker_image }}:${{ github.sha }}
            ${{ github.ref == 'refs/heads/master' && format('{0}:latest', inputs.backend_docker_image) || '' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Azure Login
        uses: azure/login@v3
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Update Azure App Service Container Image
        run: |
          az webapp config container set \
          --name ${{ inputs.backend_app_name }} \
          --resource-group ${{ inputs.resource_group_name }} \
          --docker-custom-image-name ${{ inputs.backend_docker_image }}:${{ github.sha }} \
          --docker-registry-server-url https://index.docker.io/v1/

      - name: Inject Application Secrets
        uses: azure/appservice-settings@v1
        with:
          app-name: ${{ inputs.backend_app_name }}
          app-settings-json: |
            [
              {
                "name": "DB_PASSWORD",
                "value": "${{ secrets.DB_PASSWORD }}",
                "slotSetting": false
              },
              {
                "name": "JWT_SECRET",
                "value": "${{ secrets.JWT_SECRET }}",
                "slotSetting": false
              },
              {
                "name": "AEROAPI_KEY",
                "value": "${{ secrets.AEROAPI_KEY }}",
                "slotSetting": false
              },
              {
                "name": "OPENSKY_CLIENT_ID",
                "value": "${{ secrets.OPENSKY_CLIENT_ID }}",
                "slotSetting": false
              },
              {
                "name": "OPENSKY_CLIENT_SECRET",
                "value": "${{ secrets.OPENSKY_CLIENT_SECRET }}",
                "slotSetting": false
              },
              {
                "name": "CSRF_SECRET",
                "value": "${{ secrets.CSRF_SECRET }}",
                "slotSetting": false
              },
              {
                "name": "SMTP_HOST",
                "value": "${{ secrets.SMTP_HOST }}",
                "slotSetting": false
              },
              {
                "name": "SMTP_PORT",
                "value": "${{ secrets.SMTP_PORT }}",
                "slotSetting": false
              },
              {
                "name": "SMTP_SECURE",
                "value": "${{ secrets.SMTP_SECURE }}",
                "slotSetting": false
              },
              {
                "name": "SMTP_USER",
                "value": "${{ secrets.SMTP_USER }}",
                "slotSetting": false
              },
              {
                "name": "SMTP_PASSWORD",
                "value": "${{ secrets.SMTP_PASSWORD }}",
                "slotSetting": false
              },
              {
                "name": "MAIL_FROM",
                "value": "${{ secrets.MAIL_FROM }}",
                "slotSetting": false
              },
              {
                "name": "APP_BASE_URL",
                "value": "https://${{ inputs.frontend_url }}",
                "slotSetting": false
              }
            ]
