name: daily-startup.yml
on:
  schedule:
    # 9:00 AM CET
    - cron: '0 9 * * *'
  workflow_dispatch:
  push:
    branches:
      - "feature/*"
permissions:
  id-token: write
  contents: read

jobs:
  call-deployment-engine:
    uses: ./.github/workflows/master-deployment.yml
    secrets: inherit
