name: daily-startup.yml
on:
  schedule:
    # 04:00 UTC (6:00 AM CEST) 
    - cron: '0 4 * * *'
  workflow_dispatch:
permissions:
  id-token: write
  contents: read

jobs:
  call-deployment-engine:
    uses: ./.github/workflows/master-deployment.yml
    with:
      skip_docker_build: true
    secrets: inherit
