name: master-deployment.yml
on:
  workflow_call:
    inputs:
      skip_docker_build:
        description: "Skip building and pushing new Docker images"
        required: false
        type: boolean
        default: false
    outputs:
      vm_host:
        description: "The FQDN of the database VM"
        value: ${{ jobs.infrastructure.outputs.vm_host }}
  push:
    branches:
      - master
  workflow_dispatch:

# Permissions for OIDC auth
permissions:
  id-token: write
  contents: read

env:
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_USE_OIDC: "true"

  RESOURCE_GROUP: "dev-inz-rg"
  BACKEND_APP_NAME: "dev-inz-backend-api"
  FRONTEND_APP_NAME: "dev-inz-frontend-app"
  BACKEND_DOCKER_IMAGE: "szerlok/flightanalytics-backend"
  FRONTEND_DOCKER_IMAGE: "szerlok/flightanalytics-frontend"

  TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
jobs:
  # IAC

  infrastructure:
    name: Provision Infrastructure
    uses: ./.github/workflows/infrastructure-provisioning.yml
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
      


  application:
    name: Deploy Application
    needs: infrastructure
    uses: ./.github/workflows/application-deployment.yml
    with:
      skip_docker_build: ${{ inputs.skip_docker_build }}
      vm_host: ${{ needs.infrastructure.outputs.vm_host }}
      backend_url: ${{ needs.infrastructure.outputs.backend_url }}
      frontend_url: ${{ needs.infrastructure.outputs.frontend_url }}
      resource_group_name: "dev-inz-rg"
      backend_app_name: "dev-inz-backend-api"
      frontend_app_name: "dev-inz-frontend-app"
    secrets: inherit
