name: master-deployment.yml
on:
  workflow_call:
    inputs:
      skip_docker_build:
        description: "Skip building and pushing new Docker images"
        required: false
        type: boolean
        default: false
    outputs:
      vm_host:
        description: "The FQDN of the database VM"
        value: ${{ jobs.infrastructure.outputs.vm_host }}
  push:
    branches:
      - master
  workflow_dispatch:

# Permissions for OIDC auth
permissions:
  id-token: write
  contents: read

env:
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_USE_OIDC: "true"

  RESOURCE_GROUP: "dev-inz-rg"
  BACKEND_APP_NAME: "dev-inz-backend-api"
  FRONTEND_APP_NAME: "dev-inz-frontend-app"
  BACKEND_DOCKER_IMAGE: "szerlok/flightanalytics-backend"
  FRONTEND_DOCKER_IMAGE: "szerlok/flightanalytics-frontend"

  TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
jobs:
  # IAC

  infrastructure:
    name: Provision Infrastructure
    runs-on: ubuntu-22.04
    outputs:
      name: "The FQDN of the database VM and backend URL"
      vm_host: ${{ steps.get_outputs.outputs.vm_host }}
      backend_url: ${{ steps.get_outputs.outputs.backend_url }}


    env:
      # Terraform can read it automatically
      TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Azure Login (OIDC)
        uses: azure/login@v3
        with:
          client-id: ${{ env.AZURE_CLIENT_ID }}
          tenant-id: ${{ env.AZURE_TENANT_ID }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.0"

      - name: Terraform Init, Plan and Apply
        working-directory: ./infrastructure/terraform/azure
        run: |
          terraform init -upgrade
          terraform apply -auto-approve

      - name: Get Terraform Outputs
        id: get_outputs
        working-directory: ./infrastructure/terraform/azure
        run: |
          echo "vm_host=$(terraform output -raw database_fqdn)" >> $GITHUB_OUTPUT
          echo "backend_url=$(terraform output -raw backend_url)" >> $GITHUB_OUTPUT
      

  # Frontend
  frontend:
    name: Build, Push and Deploy Frontend
    needs: infrastructure
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Login to Docker Hub
        if: ${{ !inputs.skip_docker_build }}
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        if: ${{ !inputs.skip_docker_build }}
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          target: prod
          build-args:
            INTERNAL_API_URL=${{ needs.infrastructure.outputs.backend_url }}
          tags: |
            ${{ env.FRONTEND_DOCKER_IMAGE }}:${{ github.sha }}
            ${{ github.ref == 'refs/heads/master' && format('{0}:latest', env.FRONTEND_DOCKER_IMAGE) || '' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Azure Login
        uses: azure/login@v3
        with:
          client-id: ${{ env.AZURE_CLIENT_ID }}
          tenant-id: ${{ env.AZURE_TENANT_ID }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}

      - name: Update Azure App Service Container Image
        run: |
          az webapp config container set \
          --name ${{ env.FRONTEND_APP_NAME }} \
          --resource-group ${{ env.RESOURCE_GROUP }} \
          --docker-custom-image-name ${{ env.FRONTEND_DOCKER_IMAGE }}:${{ github.sha }} \
          --docker-registry-server-url https://index.docker.io/v1/


  # Database setup:
  database-setup:
    name: Prepare Database VM
    needs: infrastructure
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "24"
          cache: 'npm'
          cache-dependency-path: ./backend/package-lock.json

      - name: Install Dependencies
        working-directory: ./backend
        run: npm ci

      # Add SSH tunnel later on, to avoid db public ip exposure


      - name: Wait for DB port
        env:
          VM_HOST: ${{ needs.infrastructure.outputs.vm_host }}
        run: |
          timeout 300s bash -c 'until printf "" 2>>/dev/null >/dev/tcp/$VM_HOST/5432; do sleep 2; done'
      - name: Run Migrations and Seeding
        working-directory: ./backend
        env:
          DB_HOST: ${{ needs.infrastructure.outputs.vm_host }}
          DB_PORT: 5432
          DB_USERNAME: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: "flight_db"

        run: npm run ci:migrate-and-seed
          
          

  # Backend - container and seeding
  backend:
    name: Build, Push and Deploy Containerized Backend
    needs: [infrastructure, database-setup]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Login to Docker Hub
        if: ${{ !inputs.skip_docker_build }}
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        if: ${{ !inputs.skip_docker_build }}
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          target: prod
          tags: |
            ${{ env.BACKEND_DOCKER_IMAGE }}:${{ github.sha }}
            ${{ github.ref == 'refs/heads/master' && format('{0}:latest', env.BACKEND_DOCKER_IMAGE) || '' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Azure Login
        uses: azure/login@v3
        with:
          client-id: ${{ env.AZURE_CLIENT_ID }}
          tenant-id: ${{ env.AZURE_TENANT_ID }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}

      - name: Update Azure App Service Container Image
        run: |
          az webapp config container set \
          --name ${{ env.BACKEND_APP_NAME }} \
          --resource-group ${{ env.RESOURCE_GROUP }} \
          --docker-custom-image-name ${{ env.BACKEND_DOCKER_IMAGE }}:${{ github.sha }} \
          --docker-registry-server-url https://index.docker.io/v1/

      - name: Inject Application Secrets
        uses: azure/appservice-settings@v1
        with:
          app-name: 'dev-inz-backend-api'
          app-settings-json: |
            [
              {
                "name": "DB_PASSWORD",
                "value": "${{ secrets.DB_PASSWORD }}",
                "slotSetting": false
              },
              {
                "name": "JWT_SECRET",
                "value": "${{ secrets.JWT_SECRET }}",
                "slotSetting": false
              },
              {
                "name": "AEROAPI_KEY",
                "value": "${{ secrets.AEROAPI_KEY }}",
                "slotSetting": false
              },
              {
                "name": "OPENSKY_CLIENT_ID",
                "value": "${{ secrets.OPENSKY_CLIENT_ID }}",
                "slotSetting": false
              },
              {
                "name": "OPENSKY_CLIENT_SECRET",
                "value": "${{ secrets.OPENSKY_CLIENT_SECRET }}",
                "slotSetting": false
              }
            ]
